# Permalinks
permalink:           pretty

# Setup
title:               Restaurant Data Analysis
tagline:             A data analysis on 10 000 restaurants all over the world.
url:                 http://monaowishee.github.io
baseurl:             /progress-for-jekyll
analytics_id:

# Owner/author information
owner:
  name:           Mona Mujib and Owishee Islam
  avatar:         avatar.png
  bio:            "UofT Students"
  #email:          alex@collectivelymade.com
  #twitter:        alexanderussell
  github:         monaowishee
  #instagram:      alexanderussell
  #dribbble:       alexanderussell
  #location:       "Lincoln, NE"


# Custom vars
version:             2.0.0
github:
  repo:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
